//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annety
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnnetyEntities : DbContext
    {
        public AnnetyEntities()
            : base("name=AnnetyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<OrdersDetails> OrdersDetails { get; set; }
        public virtual DbSet<ProductSize> ProductSize { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersOrders> UsersOrders { get; set; }
        public virtual DbSet<WatchList> WatchList { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Stocks> Stocks { get; set; }
    }
}
