//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annety
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersDetails
    {
        public int Code { get; set; }
        public int OrderCode { get; set; }
        public int StockCode { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual UsersOrders UsersOrders { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
